### ISSUE TITLE
Criar JSON com as tarefas demo

### ISSUE THREAD

**Issue by emys-alb** [emys-alb/TDAH#23]
## Descreva o erro
As [tarefas](https://github.com/emys-alb/TDAH/blob/main/App/telas/tarefas.js) que utilizamos para criar o protótipo foram criadas utilizando useState, o que não é o ideal tendo em vista que desejamos expandir a aplicação para várias crianças poderem usar.

## Comportamento esperado:
Criar uma pasta chamada 'bd' e nela conter um JSON ser usado com um objeto para representar a criança e as suas tarefas do dia.
Rota esperada: `TDAH/App/bd/nomeDaCrianca.json`

**Comment by JuanBarros2** [comment]
É só a criação do arquivo com as tarefas mesmo, né?

**Comment by emys-alb** [comment]
> É só a criação do arquivo com as tarefas mesmo, né?

Isso
